import{loadCoachCoreLoopPlayer,saveCoachCoreLoopAction}from"./coachFollowUpService.js";
import{loadPlayerAssignment,savePlayerAssignment}from"./playerAssignmentService.js";
import{COACH_FOLLOW_UP_CONTEXT_KEY as CTX,buildNextAssignmentSuggestion,getCoachResponseContext,parseCoachResponseNote,serializeCoachResponseNote}from"./coachPlayerResponseLoop.js";
const clean=v=>String(v??"").trim(),norm=v=>clean(v).toLowerCase(),parse=(v,f)=>{try{return JSON.parse(v)||f}catch{return f}};
function context(d){
 const x=globalThis[CTX]||{},s=parse(localStorage.getItem("sl:session"),{}),session=Array.isArray(s)?s[0]:s,want=norm(x.playerIdentity||document.querySelector('[data-testid="coach-players-filter-rail"] input')?.value||d.querySelector('[role="dialog"]')?.getAttribute("aria-label")),p=parse(localStorage.getItem("sl:players"),[]).find(p=>[p.email,p.player_email,p.playerId,p.player_id,p.id,p.name,p.displayName].some(v=>norm(v)===want));
 return{teamId:clean(p?.teamId||p?.team_id||session?.teamId||session?.team_id),playerIdentity:clean(p?.email||p?.player_email||p?.playerId||p?.player_id||p?.id||want).toLowerCase(),playerName:clean(x.playerName||p?.name||p?.displayName||d.querySelector('[role="dialog"]')?.getAttribute("aria-label")||"Player")};
}
function retire(){for(const b of document.querySelectorAll("#coach-roster-operations button"))if(/^(?:✓\s*)?NUDGE$/i.test(clean(b.textContent))){b.hidden=b.disabled=true;b.dataset.shotlabLegacyNudgeRetired="true"}}
const markup='<section data-testid="coach-follow-up-ledger" data-follow-up-state="none" style="display:grid;gap:10px;margin-top:14px;min-width:0"><div data-r hidden><strong></strong></div><div data-d hidden><strong></strong></div><label>Next assignment to deliver<textarea data-testid="coach-next-assignment-input" maxlength="2000" style="display:block;width:100%;min-height:84px;box-sizing:border-box"></textarea></label><button data-send style="min-height:44px">Deliver next assignment</button><label>Private coach note<textarea maxlength="2000" style="display:block;width:100%;min-height:84px;box-sizing:border-box"></textarea></label><div><button data-primary style="min-height:44px">Mark for follow-up</button><button data-clear style="min-height:44px">Clear record</button></div><p>The player receives only the assignment text and result context. Private coach notes remain coach-only.</p><div role="status"></div></section>';
function mount(host,c){
 host.innerHTML=markup;const q=s=>host.querySelector(s),panel=q("section"),a=q('[data-testid="coach-next-assignment-input"]'),n=q("label:nth-of-type(2) textarea"),send=q("[data-send]"),primary=q("[data-primary]"),clear=q("[data-clear]"),status=q('[role="status"]'),result=q("[data-r]"),delivery=q("[data-d]"),buttons=[send,primary,clear],saveInFlightRef={current:false};let record,response,saving=false;
 const setDelivery=v=>{delivery.hidden=!v;if(v){delivery.dataset.testid="coach-player-assignment-status";delivery.dataset.assignmentState=v.state||"";delivery.querySelector("strong").textContent=v.state==="completed"?"Player completed":v.state==="started"?"Player started":v.state==="acknowledged"?"Player acknowledged":"Delivered"}else delete delivery.dataset.testid};
 const setSaving=v=>{saving=!!v;const busyProps={"aria-busy": saving};for(const b of buttons)b.setAttribute("aria-busy",String(busyProps["aria-busy"]))};
 const refresh=()=>{response=getCoachResponseContext({playerIdentity:c.playerIdentity,playerName:c.playerName});if(!response)return;result.hidden=false;result.dataset.testid="coach-result-response-context";result.querySelector("strong").textContent=response.resultDetail||"Training result recorded";if(!a.value)a.value=buildNextAssignmentSuggestion(response)};host.__shotlabRefresh=refresh;refresh();
 const paint=msg=>{const state=record?.state==="dismissed"?"":record?.state||"";panel.dataset.followUpState=state||"none";primary.textContent=state==="planned"?"Mark follow-up complete":state==="completed"?"Reopen follow-up":"Mark for follow-up";for(const b of buttons)b.disabled=saving;clear.disabled=saving||!state;if(msg)status.textContent=msg};
 const save=async(state,deliver=false)=>{
  if(deliver&&!clean(a.value)){status.textContent="Add a next assignment before recording it.";return}
  if (saveInFlightRef.current) return;
  saveInFlightRef.current = true;setSaving(true);paint("Saving…");
  try{const [follow,deliveryResult]=await Promise.all([saveCoachCoreLoopAction({...c,state,note:serializeCoachResponseNote({assignment:a.value,privateNote:n.value})}),deliver?savePlayerAssignment({...c,assignmentText:a.value,resultDetail:response?.resultDetail||""}):null]);record=follow.record||record;if (deliveryResult?.ok && deliveryResult.assignment) setDelivery(deliveryResult.assignment);paint(deliver?(deliveryResult?.ok?(deliveryResult.message||"Assignment delivered to the player."):(follow.ok?"Private follow-up saved. Player delivery could not be confirmed. Retry when connected.":"Saved locally, but team sync and player delivery could not be confirmed. Retry when connected.")):(follow.message||(follow.ok?"Follow-up record saved.":"Follow-up could not be synced. Retry when connected.")))}
  catch{paint(deliver?"Player delivery could not be confirmed. Retry when connected.":"Follow-up could not be saved. Try again.")}
  finally {saveInFlightRef.current = false;setSaving(false);paint()}
 };
 send.onclick=()=>save("planned",true);primary.onclick=()=>save(record?.state==="planned"?"completed":"planned");clear.onclick=()=>save("dismissed");paint("Loading follow-up record…");
 Promise.all([loadCoachCoreLoopPlayer(c),loadPlayerAssignment(c)]).then(([follow,deliveryResult])=>{record=follow.record||null;const confirmedDelivery = deliveryResult.ok ? deliveryResult.assignment || null : null;setDelivery(confirmedDelivery);refresh();const note=parseCoachResponseNote(follow.record?.note||"");a.value=deliveryResult.assignment?.assignmentText||note.assignment||a.value;n.value=note.privateNote;paint(record?"Existing follow-up record loaded.":response?"Result loaded. Confirm the next assignment before recording it.":"No follow-up has been recorded.")}).catch(()=>paint("Follow-up could not be loaded. Retry when connected."));
}
export function installCoachFollowUpEnhancer(){
 if(typeof window==="undefined"||typeof document==="undefined")return false;if(window.__shotlabCoachFollowUpEnhancer)return true;window.__shotlabCoachFollowUpEnhancer=true;let host,drawer,key="",frame;
 const run=()=>{frame=null;retire();const d=document.querySelector('[data-testid="coach-player-intelligence-drawer"]');if(!d){host?.remove();host=drawer=null;key="";return}const c=context(d),k=c.teamId+"::"+c.playerIdentity;if(!c.teamId||!c.playerIdentity)return;if(d===drawer&&host?.isConnected&&k===key){host.__shotlabRefresh?.();return}host?.remove();drawer=d;key=k;const dialog=d.querySelector('[role="dialog"]');const body=dialog?.querySelector('[data-visual-role="dashboard-section"]')?.parentElement;if(!body||body===dialog)return;host=document.createElement("div");host.dataset.testid="coach-follow-up-ledger-host";body.appendChild(host);mount(host,c)};
 const schedule=()=>{if(frame==null)frame=requestAnimationFrame(run)};new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});window.addEventListener("storage",schedule);schedule();return true;
}
