import{openExactPlayerFollowUp}from"./coachAssignmentOutcomeEnhancer.js";
import{loadCoachCoreLoopPlayer,saveCoachCoreLoopAction}from"./coachFollowUpService.js";
import{loadPlayerAssignment,savePlayerAssignment}from"./playerAssignmentService.js";
const CTX="__shotlabCoachFollowUpContext",RESPONSE="__shotlabCoachResponseContext",NEXT="[SHOTLAB NEXT ASSIGNMENT]",PRIVATE="[SHOTLAB PRIVATE NOTE]",clean=v=>String(v??"").trim(),norm=v=>clean(v).toLowerCase(),parse=(v,f)=>{try{return JSON.parse(v)||f}catch{return f}};
const noteParse=v=>{v=clean(v);if(!v.startsWith(NEXT))return{assignment:"",privateNote:v};const b=v.slice(NEXT.length).trim(),i=b.indexOf(PRIVATE);return i<0?{assignment:b,privateNote:""}:{assignment:clean(b.slice(0,i)),privateNote:clean(b.slice(i+PRIVATE.length))}},noteSave=(a,n)=>clean(a)?NEXT+"\n"+clean(a)+(clean(n)?"\n"+PRIVATE+"\n"+clean(n):""):clean(n);
function responseFor(c){const x=globalThis[RESPONSE];if(!x)return null;const want=[norm(c.playerIdentity),norm(c.playerName)],have=[norm(x.playerIdentity),norm(x.playerName)];if(!want.some(v=>v&&have.includes(v)))return null;const t=Date.parse(x.openedAt||"");return Number.isFinite(t)&&Date.now()-t>6e5?null:x}
function context(d){const x=globalThis[CTX]||{},s=parse(localStorage.getItem("sl:session"),{}),session=Array.isArray(s)?s[0]:s,want=norm(x.playerIdentity||d.querySelector('[role="dialog"]')?.getAttribute("aria-label")),p=parse(localStorage.getItem("sl:players"),[]).find(p=>[p.email,p.player_email,p.id,p.name,p.displayName].some(v=>norm(v)===want));return{teamId:clean(p?.teamId||p?.team_id||session?.teamId||session?.team_id),playerIdentity:clean(p?.email||p?.player_email||p?.id||want).toLowerCase(),playerName:clean(x.playerName||p?.name||p?.displayName||d.querySelector('[role="dialog"]')?.getAttribute("aria-label")||"Player")}}
function retire(){for(const b of document.querySelectorAll("#coach-roster-operations button"))if(/NUDGE/i.test(clean(b.textContent))){b.hidden=b.disabled=true;b.dataset.shotlabLegacyNudgeRetired="true"}}
const markup='<section data-testid="coach-follow-up-ledger" data-follow-up-state="none" style="display:grid;gap:10px;min-width:0"><div data-r hidden></div><div data-d hidden></div><label>Next assignment to deliver<textarea data-testid="coach-next-assignment-input" maxlength="2000" style="width:100%;min-height:84px;box-sizing:border-box"></textarea></label><button data-send style="min-height:44px">Deliver next assignment</button><label>Private coach note<textarea maxlength="2000" style="width:100%;min-height:84px;box-sizing:border-box"></textarea></label><button data-primary style="min-height:44px">Mark for follow-up</button><button data-clear style="min-height:44px">Clear record</button><p>The player receives only the assignment text and result context. Private coach notes remain coach-only.</p><div role="status"></div></section>';
function mount(host,c){
 host.innerHTML=markup;const q=s=>host.querySelector(s),panel=q("section"),a=q('[data-testid="coach-next-assignment-input"]'),n=q("label:nth-of-type(2) textarea"),send=q("[data-send]"),primary=q("[data-primary]"),clear=q("[data-clear]"),status=q('[role="status"]'),result=q("[data-r]"),delivery=q("[data-d]"),saveInFlightRef={current:false};let record,response,saving=false;
 const setDelivery=v=>{delivery.hidden=!v;if(v){delivery.dataset.testid="coach-player-assignment-status";delivery.dataset.assignmentState=v.state||"";delivery.textContent="Delivered"}else delete delivery.dataset.testid};
 const setSaving=v=>{saving=!!v;const busyProps={"aria-busy": saving};for(const b of[send,primary,clear])b.setAttribute("aria-busy",String(busyProps["aria-busy"]))};
 const refresh=()=>{response=responseFor(c);if(response){result.hidden=false;result.dataset.testid="coach-result-response-context";result.textContent=response.resultDetail||"Training result recorded";if(!a.value)a.value=response.made?"Repeat this shooting block and match or improve "+response.made+" makes with the same standard.":"Review this result and complete the next agreed training block."}};host.__shotlabRefresh=refresh;refresh();
 const paint=msg=>{const state=record?.state==="dismissed"?"":record?.state||"";panel.dataset.followUpState=state||"none";primary.textContent=state==="planned"?"Mark follow-up complete":state==="completed"?"Reopen follow-up":"Mark for follow-up";send.disabled=primary.disabled=saving;clear.disabled=saving||!state;if(msg)status.textContent=msg};
 const save=async(state,deliver=false)=>{if(deliver&&!a.value.trim()){status.textContent="Add a next assignment before recording it.";return}if (saveInFlightRef.current) return;saveInFlightRef.current = true;setSaving(true);paint("Saving…");try{const [follow,deliveryResult]=await Promise.all([saveCoachCoreLoopAction({...c,state,note:noteSave(a.value,n.value)}),deliver?savePlayerAssignment({...c,assignmentText:a.value,resultDetail:response?.resultDetail||""}):null]);record=follow.record||record;if (deliveryResult?.ok && deliveryResult.assignment) setDelivery(deliveryResult.assignment);paint(deliver?(deliveryResult?.ok?(deliveryResult.message||"Assignment delivered to the player."):(follow.ok?"Private follow-up saved. Player delivery could not be confirmed. Retry when connected.":"Saved locally, but team sync and player delivery could not be confirmed. Retry when connected.")):(follow.message||"Follow-up record saved."))}catch{paint(deliver?"Player delivery could not be confirmed. Retry when connected.":"Follow-up could not be saved. Try again.")}finally {saveInFlightRef.current = false;setSaving(false);paint()}};
 send.onclick=()=>save("planned",true);primary.onclick=()=>save(record?.state==="planned"?"completed":"planned");clear.onclick=()=>save("dismissed");paint("Loading follow-up record…");
 Promise.all([loadCoachCoreLoopPlayer(c),loadPlayerAssignment(c)]).then(([follow,deliveryResult])=>{record=follow.record||null;const confirmedDelivery = deliveryResult.ok ? deliveryResult.assignment || null : null;setDelivery(confirmedDelivery);refresh();const parsed=noteParse(follow.record?.note||"");a.value=deliveryResult.assignment?.assignmentText||parsed.assignment||a.value;n.value=parsed.privateNote;paint(record?"Existing follow-up record loaded.":response?"Result loaded. Confirm the next assignment before recording it.":"No follow-up has been recorded.")}).catch(()=>paint("Follow-up could not be loaded. Retry when connected."));
}
function activateRow(row){const name=clean(row?.querySelector?.("strong")?.textContent),detail=clean(row?.querySelector?.("small")?.textContent),meta=clean(row?.querySelector?.("time")?.textContent);if(!name||!detail||!/makes?|shoot|drill|score|strength|s&c|logged|completed/i.test(detail))return false;const m=detail.match(/(?:^|\D)(\d{1,5})\s+makes?\b/i),identity=norm(name);globalThis[RESPONSE]={playerIdentity:identity,playerName:name,resultDetail:detail,resultMeta:meta,made:m?+m[1]:0,openedAt:new Date().toISOString()};globalThis[CTX]={playerIdentity:identity,playerName:name};openExactPlayerFollowUp({searchIdentity:name,name});return true}
export function installCoachFollowUpEnhancer(){
 if(typeof window==="undefined"||typeof document==="undefined")return false;if(window.__shotlabCoachFollowUpEnhancer)return true;window.__shotlabCoachFollowUpEnhancer=true;let host,drawer,key="",frame;
 const run=()=>{frame=null;retire();for(const row of document.querySelectorAll('[data-testid="coach-live-activity"] .mcTimeline>div')){const name=clean(row.querySelector("strong")?.textContent),detail=clean(row.querySelector("small")?.textContent),ok=name&&detail&&/makes?|shoot|drill|score|strength|s&c|logged|completed/i.test(detail);if(ok){row.dataset.shotlabResponseRow="true";row.setAttribute("role","button");row.setAttribute("tabindex","0");row.setAttribute("aria-label","Review "+name+" result and record next assignment")}}const d=document.querySelector('[data-testid="coach-player-intelligence-drawer"]');if(!d){host?.remove();host=drawer=null;key="";return}const c=context(d),k=c.teamId+"::"+c.playerIdentity;if(!c.teamId||!c.playerIdentity)return;if(d===drawer&&host?.isConnected&&k===key){host.__shotlabRefresh?.();return}host?.remove();drawer=d;key=k;const dialog=d.querySelector('[role="dialog"]'),body=dialog?.querySelector('[data-visual-role="dashboard-section"]')?.parentElement;if(!body||body===dialog)return;host=document.createElement("div");host.dataset.testid="coach-follow-up-ledger-host";body.appendChild(host);mount(host,c)};
 const open=e=>{const row=e.target?.closest?.('[data-testid="coach-live-activity"] .mcTimeline>div[data-shotlab-response-row="true"]');if(row)activateRow(row)};document.addEventListener("click",open,true);document.addEventListener("keydown",e=>{if((e.key==="Enter"||e.key===" ")&&e.target?.matches?.('[data-shotlab-response-row="true"]')){e.preventDefault();activateRow(e.target)}});const schedule=()=>{if(frame==null)frame=requestAnimationFrame(run)};new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true,characterData:true});schedule();return true;
}
