import { isDemoPlayerSessionShotLog } from "./demoMode.js";

const STORAGE_KEYS=Object.freeze({teams:"sl:teams",players:"sl:players",playerProfiles:"sl:player-profiles",events:"sl:events",rsvps:"sl:rsvps",scores:"sl:scores",programScores:"sl:program-scores",shotLogs:"sl:shotlogs",challenges:"sl:challenges",scSessions:"sl:sc-sessions",scRsvps:"sl:sc-rsvps",scLogs:"sl:sc-logs",coachPriorities:"sl:coach-priorities",progressSnapshots:"sl:progress-snapshots",demoMeta:"sl:demo-data-meta"});
const DEMO_TEAM_ID="team-demo-titans";
const DEMO_DATA_VERSION=7;
const DEMO_TIMESTAMP=Date.parse("2026-03-20T12:00:00.000Z");
const DEMO_TEAM_BRANDING=Object.freeze({teamName:"Demo Titans",logoUrl:"/branding/titans-exact-logo.png.PNG",logoMarkUrl:"/branding/titans-default-mark.svg"});

const padDatePart=(value)=>String(value).padStart(2,"0");
export const localDateKey=(value=new Date())=>{const date=value instanceof Date?value:new Date(value);return `${date.getFullYear()}-${padDatePart(date.getMonth()+1)}-${padDatePart(date.getDate())}`;};
const relativeDate=(days=0)=>{const date=new Date();date.setHours(12,0,0,0);date.setDate(date.getDate()+days);return localDateKey(date);};
const relativeTimestamp=(days=0,hour=18,minute=0)=>{const date=new Date();date.setHours(hour,minute,0,0);date.setDate(date.getDate()+days);return date.getTime();};
const rows=(value)=>value.split(";").map((row)=>row.split("|"));

const demoRoster=rows("marcus-reed|Marcus|Reed|3|PG|12|782|9|127|15|24|36|40;jordan-mitchell|Jordan|Mitchell|11|SG|11|714|7|95|14|23|34|38;micah-santos|Micah|Santos|24|SF|12|661|6|123|13|22|32|36;isaiah-brooks|Isaiah|Brooks|5|PG|10|623|5|63|12|21|31|35;cameron-hayes|Cameron|Hayes|14|SG|11|579|5|125|11|20|29|34;noah-bennett|Noah|Bennett|21|PF|12|531|4|119|11|20|28|32;devin-walker|Devin|Walker|32|C|11|486|3|91|10|19|27|31;miles-thompson|Miles|Thompson|1|G|10|428|2|109|9|18|25|29;jalen-price|Jalen|Price|20|F|10|371|2|51|8|17|24|27;caleb-foster|Caleb|Foster|23|F|9|304|1|85|7|16|22|25;andre-lewis|Andre|Lewis|34|C|9|218|0|74|6|15|20|23;primary|Demo|Player|12|G|11|552|4|111|11|20|29|33|1").map(([slug,firstName,lastName,jerseyNumber,position,grade,weeklyMakes,streakDays,attendanceMask,warmup,form,programA,programB,primary])=>({slug,email:primary?"demo@shotlab.app":`${slug.replace("-", ".")}@demo.shotlab.app`,firstName,lastName,jerseyNumber,position,grade,weeklyMakes:+weeklyMakes,streakDays:+streakDays,attendanceMask:+attendanceMask,warmup:+warmup,form:+form,program:[+programA,+programB],primary:Boolean(primary)}));
const playerName=(player)=>`${player.firstName} ${player.lastName}`;
const playerId=(player)=>player.primary?"player-demo-primary":`player-demo-${player.slug}`;
const attended=(player,index)=>Boolean(player.attendanceMask&(1<<index));

const basePlayers=demoRoster.map((player,index)=>({id:playerId(player),email:player.email,name:playerName(player),role:"player",hideFromLeaderboards:false,createdAt:DEMO_TIMESTAMP+index}));
const basePlayerProfiles=demoRoster.map((player,index)=>({id:player.primary?"profile-demo-primary":`profile-demo-${player.slug}`,userId:player.email,email:player.email,firstName:player.firstName,lastName:player.lastName,jerseyNumber:player.jerseyNumber,position:player.position,grade:player.grade,createdAt:DEMO_TIMESTAMP+index}));

const baseEvents=rows("event-demo-open-gym|Open Gym + Competitive Shooting|-24|5:30 PM|Main Gym|workout;event-demo-advantage-reads|Advantage Reads Lab|-16|6:00 PM|Aux Gym|clinic;event-demo-team-practice-past|Team Practice|-9|6:15 PM|Main Gym|practice;event-demo-lift-past|Team Lift + Recovery|-4|6:30 AM|Weight Room|strength;evt-upcoming-1|Team Practice|1|6:00 PM|Main Gym|practice;event-demo-skill-lab|Skill Lab: Rim Pressure|3|6:15 PM|Main Gym Court 2|workout;event-demo-shooting-club|Early Work 300|5|6:30 AM|Aux Gym|shooting;event-demo-film-room|Film + Recovery Reset|8|4:45 PM|Team Room|recovery;event-demo-scrimmage|Blue / White Scrimmage|10|10:00 AM|Main Gym|game").map(([id,title,days,time,location,type])=>({id,title,date:relativeDate(+days),time,location,type}));
const baseRsvps=baseEvents.slice(0,7).flatMap((event,eventIndex)=>demoRoster.map((player,playerIndex)=>({id:`rsvp-demo-${eventIndex+1}-${player.slug}`,email:player.email,playerId:player.email,name:playerName(player),eventId:event.id,attended:attended(player,eventIndex),status:attended(player,eventIndex)?"going":"not-going",ts:relativeTimestamp(eventIndex-6,16,playerIndex*2)})));

const homeScore=(player,suffix,drillId,drillName,score,days,minute)=>({id:`score-${player.slug}-${suffix}`,email:player.email,playerId:player.email,name:playerName(player),drillId,drillName,score,date:relativeDate(days),ts:relativeTimestamp(days,18,minute),src:"home"});
const demoPrimaryScores=demoRoster.flatMap((player,index)=>[
  homeScore(player,"warmup","demo-home-warm-up-shooting-4-minute","4-Minute Warm-Up Shooting",player.warmup,index%3===0?0:-1,index*2),
  homeScore(player,"form","demo-form-shooting","Form Shooting Ladder",player.form,-2-(index%2),index*2+1)
]);
const demoShotLogs=demoRoster.flatMap((player,index)=>{const first=Math.round(player.weeklyMakes*.4),second=Math.round(player.weeklyMakes*.33);return [first,second,player.weeklyMakes-first-second].map((made,slot)=>{const days=slot===0?(index%2===0?0:-1):slot===1?-3:-6;return {id:`shotlog-${player.slug}-${slot+1}`,email:player.email,playerId:player.email,name:playerName(player),made,date:relativeDate(days),ts:relativeTimestamp(days,19,index+slot*12)};});});
const demoProgressSnapshots=demoRoster.map((player,index)=>({id:`progress-${player.slug}`,email:player.email,playerId:player.email,label:"7-day makes",value:player.weeklyMakes,date:relativeDate(0),ts:relativeTimestamp(0,20,index)}));
const demoProgramScores=demoRoster.flatMap((player,index)=>player.program.map((score,slot)=>{const days=slot?-2-(index%3):-7-(index%2);return {id:`program-${player.slug}-${slot+1}`,email:player.email,playerId:player.email,name:playerName(player),drillId:"demo-program-230s",drillName:"2:30 Shooting",score,date:relativeDate(days),ts:relativeTimestamp(days,18,index+slot*15),src:"program"};}));
const demoChallenges=[{id:"challenge-demo-pending",playerId:"marcus.reed@demo.shotlab.app",from:"marcus.reed@demo.shotlab.app",fromName:"Marcus Reed",to:"demo@shotlab.app",toName:"Demo Player",drillId:"demo-home-warm-up-shooting-4-minute",score:15,max:25,status:"pending",ts:relativeTimestamp(-1,20,5)}];

const demoScSessions=rows("sc-demo-recovery|Recovery + Mobility|Recovery|-6|6:30 AM|Performance Center;sc-demo-power|Total Body Strength|Strength|2|6:15 AM|Weight Room").map(([id,title,sport,days,time,location])=>({id,title,sport,date:relativeDate(+days),time,location,sessionType:"Program"}));
const demoScRsvps=demoScSessions.flatMap((session,sessionIndex)=>demoRoster.map((player,playerIndex)=>({id:`scrsvp-${sessionIndex}-${player.slug}`,sessionId:session.id,email:player.email,playerId:player.email,name:playerName(player),status:attended(player,(sessionIndex+2)%7)?"going":"not-going",attended:sessionIndex===0?attended(player,2):undefined,ts:relativeTimestamp(-7+sessionIndex*4,12,playerIndex)})));
const demoCoachPriorities={todayFocusText:"Raise team shooting volume and close tomorrow's RSVP gaps.",focusEmphasis:"Consistency",priorityDrillText:"2:30 Shooting",challengeText:"Get 10 players over 500 weekly makes.",weeklyMakesTarget:650,weeklyCheckinsTarget:3};

function clone(value){return JSON.parse(JSON.stringify(value));}
function buildDemoTeam(teamId,coachEmail,team){
  if(team){const existing=clone(team),currentName=String(existing?.name||"").trim(),currentBrandingName=String(existing?.branding?.teamName||"").trim(),shouldSeedDemoIdentity=(!currentName||/^(demo team|shotlab team)$/i.test(currentName))&&(!currentBrandingName||/^(demo team|shotlab team)$/i.test(currentBrandingName));return {...existing,id:teamId||existing.id,...(shouldSeedDemoIdentity?{name:"Demo Titans",teamName:DEMO_TEAM_BRANDING.teamName,logoUrl:DEMO_TEAM_BRANDING.logoUrl,logoMarkUrl:DEMO_TEAM_BRANDING.logoMarkUrl,branding:{...(existing.branding||{}),...DEMO_TEAM_BRANDING}}:{}),ownerCoachId:coachEmail||existing.ownerCoachId||existing.coachEmail||null};
  }
  return {id:teamId||DEMO_TEAM_ID,name:"Demo Titans",teamName:DEMO_TEAM_BRANDING.teamName,logoUrl:DEMO_TEAM_BRANDING.logoUrl,logoMarkUrl:DEMO_TEAM_BRANDING.logoMarkUrl,branding:{...DEMO_TEAM_BRANDING},ownerCoachId:coachEmail||null,createdAt:DEMO_TIMESTAMP,joinCode:"DEMO26",updatedAt:Date.now()};
}
const withTeam=(rows,teamId)=>rows.map((row)=>({...row,teamId}));

export function buildDemoDataBundle({teamId=DEMO_TEAM_ID,coachEmail=null,team}={}){
  const resolvedTeam=buildDemoTeam(teamId,coachEmail,team),playerRows=withTeam(basePlayers,resolvedTeam.id),coachRow=coachEmail?{id:"coach-demo-primary",email:coachEmail,name:"Demo Coach",role:"coach",isCoach:true,teamId:resolvedTeam.id,hideFromLeaderboards:true,createdAt:DEMO_TIMESTAMP-1}:null;
  return {teams:[resolvedTeam],players:coachRow?[coachRow,...playerRows]:playerRows,playerProfiles:withTeam(basePlayerProfiles,resolvedTeam.id),events:withTeam(baseEvents,resolvedTeam.id),rsvps:withTeam(baseRsvps,resolvedTeam.id),scores:withTeam(demoPrimaryScores,resolvedTeam.id),programScores:withTeam(demoProgramScores,resolvedTeam.id),shotLogs:withTeam(demoShotLogs,resolvedTeam.id),challenges:withTeam(demoChallenges,resolvedTeam.id),scSessions:withTeam(demoScSessions,resolvedTeam.id).map((session)=>({...session,ownerCoachId:coachEmail||"coach.demo@shotlab.app"})),scRsvps:withTeam(demoScRsvps,resolvedTeam.id),scLogs:[],coachPriorities:{...demoCoachPriorities,updatedAt:new Date().toISOString()},progressSnapshots:withTeam(demoProgressSnapshots,resolvedTeam.id),demoMeta:{seededAt:Date.now(),teamId:resolvedTeam.id,coachEmail,source:"demo-data",version:DEMO_DATA_VERSION,rosterSize:demoRoster.length}};
}

function parseStored(value,fallback){if(value==null)return fallback;if(typeof value!=="string")return value;try{return JSON.parse(value);}catch{return fallback;}}
export function unwrapManagedStorageValue(result){if(result&&typeof result==="object"&&Object.prototype.hasOwnProperty.call(result,"value"))return result.value;return result;}
async function readStored(key,fallback){if(typeof window==="undefined")return fallback;try{if(window.storage&&typeof window.storage.get==="function"){const result=await window.storage.get(key),parsed=parseStored(unwrapManagedStorageValue(result),null);if(parsed!=null)return parsed;}}catch{}return parseStored(window.localStorage?.getItem(key),fallback);}
async function writeStored(key,value){const json=JSON.stringify(value);if(typeof window==="undefined")return;if(window.localStorage)window.localStorage.setItem(key,json);if(window.storage&&typeof window.storage.set==="function")await window.storage.set(key,json,true);}
const normalizeIdentity=(value)=>String(value||"").trim().toLowerCase();
const rowTeamId=(row)=>String(row?.teamId??row?.team_id??"").trim();
function demoIdentitySet(payload){const identities=new Set();for(const row of [...(payload.players||[]),...(payload.playerProfiles||[])])for(const value of [row.email,row.playerId,row.player_id,row.userId,row.user_id]){const normalized=normalizeIdentity(value);if(normalized)identities.add(normalized);}return identities;}
function rowUsesManagedDemoIdentity(row,identities){return [row?.email,row?.player_email,row?.playerEmail,row?.playerId,row?.player_id,row?.userId,row?.user_id].map(normalizeIdentity).some((value)=>value&&identities.has(value));}

export function mergeDemoCollection(existing,incoming,{teamId="",managedIdentities=new Set(),teamsOnly=false}={}){const prior=Array.isArray(existing)?existing:[],next=Array.isArray(incoming)?incoming:[],incomingIds=new Set(next.map((row)=>String(row?.id||"")).filter(Boolean)),preserved=prior.filter((row)=>{if(incomingIds.has(String(row?.id||"")))return false;if(teamsOnly)return String(row?.id||"")!==String(teamId||"");if(teamId&&rowTeamId(row)===String(teamId))return false;if(rowUsesManagedDemoIdentity(row,managedIdentities))return false;return true;});return [...preserved,...next];}

export async function applyDemoData(bundle){
  const payload=bundle||buildDemoDataBundle(),teamId=String(payload.demoMeta?.teamId||payload.teams?.[0]?.id||""),managedIdentities=demoIdentitySet(payload),collections=[[STORAGE_KEYS.teams,payload.teams||[],{teamsOnly:true}],[STORAGE_KEYS.players,payload.players||[]],[STORAGE_KEYS.playerProfiles,payload.playerProfiles||[]],[STORAGE_KEYS.events,payload.events||[]],[STORAGE_KEYS.rsvps,payload.rsvps||[]],[STORAGE_KEYS.scores,payload.scores||[]],[STORAGE_KEYS.programScores,payload.programScores||[]],[STORAGE_KEYS.shotLogs,payload.shotLogs||[]],[STORAGE_KEYS.challenges,payload.challenges||[]],[STORAGE_KEYS.scSessions,payload.scSessions||[]],[STORAGE_KEYS.scRsvps,payload.scRsvps||[]],[STORAGE_KEYS.scLogs,payload.scLogs||[]],[STORAGE_KEYS.progressSnapshots,payload.progressSnapshots||[]]];
  for(const [key,incoming,options={}] of collections){const existing=await readStored(key,[]);await writeStored(key,mergeDemoCollection(existing,incoming,{teamId,managedIdentities,...options}));}
  const existingPriorities=await readStored(STORAGE_KEYS.coachPriorities,{}),priorityMap=existingPriorities&&typeof existingPriorities==="object"&&!Array.isArray(existingPriorities)?existingPriorities:{};await writeStored(STORAGE_KEYS.coachPriorities,{...priorityMap,[teamId]:payload.coachPriorities||demoCoachPriorities});await writeStored(STORAGE_KEYS.demoMeta,payload.demoMeta||{});
}

export async function clearDemoData(bundle){
  const payload=bundle||buildDemoDataBundle({coachEmail:"coach.demo@shotlab.app"}),storedMeta=await readStored(STORAGE_KEYS.demoMeta,{}),teamId=String(storedMeta?.teamId||payload.demoMeta?.teamId||payload.teams?.[0]?.id||DEMO_TEAM_ID),managedIdentities=demoIdentitySet(payload),storedCoachEmail=normalizeIdentity(storedMeta?.coachEmail);if(storedCoachEmail)managedIdentities.add(storedCoachEmail);managedIdentities.add("coach.demo@shotlab.app");managedIdentities.add("demo@shotlab.app");
  const collections=[[STORAGE_KEYS.teams,{teamsOnly:true}],[STORAGE_KEYS.players],[STORAGE_KEYS.playerProfiles],[STORAGE_KEYS.events],[STORAGE_KEYS.rsvps],[STORAGE_KEYS.scores],[STORAGE_KEYS.programScores],[STORAGE_KEYS.shotLogs],[STORAGE_KEYS.challenges],[STORAGE_KEYS.scSessions],[STORAGE_KEYS.scRsvps],[STORAGE_KEYS.scLogs],[STORAGE_KEYS.progressSnapshots]];
  for(const [key,options={}] of collections){const existing=await readStored(key,[]),preserved=(Array.isArray(existing)?existing:[]).filter((row)=>{if(options.teamsOnly)return String(row?.id||"")!==teamId;if(rowTeamId(row)===teamId)return false;if(rowUsesManagedDemoIdentity(row,managedIdentities))return false;if(key===STORAGE_KEYS.shotLogs&&isDemoPlayerSessionShotLog(row,{teamId}))return false;return true;});await writeStored(key,preserved);}
  const priorities=await readStored(STORAGE_KEYS.coachPriorities,{});if(priorities&&typeof priorities==="object"&&!Array.isArray(priorities)){const nextPriorities={...priorities};delete nextPriorities[teamId];await writeStored(STORAGE_KEYS.coachPriorities,nextPriorities);}await writeStored(STORAGE_KEYS.demoMeta,{});
}

function installLegacyDemoMigrationMarker(){if(typeof window==="undefined"||typeof window.addEventListener!=="function")return;window.addEventListener("shotlab:demo-session-started",(event)=>{try{const accountEmail=normalizeIdentity(event?.detail?.email);if(accountEmail!=="coach.demo@shotlab.app"&&accountEmail!=="demo@shotlab.app")return;const players=parseStored(window.localStorage?.getItem(STORAGE_KEYS.players),[]),teams=parseStored(window.localStorage?.getItem(STORAGE_KEYS.teams),[]),rows=Array.isArray(players)?players:[],demoPlayer=rows.find((row)=>normalizeIdentity(row?.email)==="demo@shotlab.app"&&row?.teamId),demoCoach=rows.find((row)=>normalizeIdentity(row?.email)==="coach.demo@shotlab.app"&&row?.teamId),ownedTeam=(Array.isArray(teams)?teams:[]).find((row)=>normalizeIdentity(row?.ownerCoachId||row?.coachEmail)==="coach.demo@shotlab.app"),teamId=String(demoPlayer?.teamId||demoCoach?.teamId||ownedTeam?.id||"").trim();if(!teamId)return;const json=JSON.stringify({seededAt:Date.now(),teamId,coachEmail:"coach.demo@shotlab.app",source:"demo-data",version:DEMO_DATA_VERSION,migration:"legacy-demo-session"});window.localStorage?.setItem(STORAGE_KEYS.demoMeta,json);if(window.storage&&typeof window.storage.set==="function")Promise.resolve(window.storage.set(STORAGE_KEYS.demoMeta,json,true)).catch(()=>{});}catch{}});}
installLegacyDemoMigrationMarker();