import { normalizeIdentity, parseStored, readRequester, readSession, requestSignedBody, signedStorageMode } from "./apiFetchBridge.js";
import { pendingId, pendingOwner, pendingTeam, reconcilePendingIds, savePending } from "./scorePersistenceService.js";

const KEY="sl:pp",activeTeam=(storage)=>String(readSession(storage)?.teamId||readSession(storage)?.team_id||"").trim(),player=(row)=>normalizeIdentity(row?.player_email||row?.playerEmail||row?.player_id||row?.playerId||row?.email);
export function reconcilePendingProgramScoreRows(options={}){return reconcilePendingIds({...options,key:KEY,teamId:options.teamId||activeTeam(options.storage)})}

export function createProgramScorePersistenceService({fetchImpl=globalThis?.fetch,storage=globalThis?.localStorage}={}){
  const request=(method,data,teamId="")=>{if(typeof fetchImpl!=="function")throw new Error("program_score_api_unavailable");return requestSignedBody(fetchImpl,`/v1/program-scores${teamId?`?team_id=${encodeURIComponent(teamId)}`:""}`,method,storage,data,`program_score_${method==="GET"?"load":method==="POST"?"write":"delete"}_failed`)};
  const loadProgramScores=async({teamId=""}={})=>{const local=parseStored(storage,"sl:program-scores",[]),scope=teamId||activeTeam(storage);if(typeof fetchImpl!=="function")return{ok:false,unavailable:true,programScores:reconcilePendingProgramScoreRows({storage,requester:readRequester(storage),teamId:scope,localRows:local,remoteRows:[]})};const body=await request("GET",null,String(teamId||"").trim());return{ok:true,storageMode:signedStorageMode(body),programScores:reconcilePendingProgramScoreRows({storage,requester:readRequester(storage),teamId:scope,localRows:local,remoteRows:Array.isArray(body?.program_scores)?body.program_scores:[]})}};
  const upsertProgramScores=async(programScores=[])=>{const rows=Array.isArray(programScores)?programScores:[programScores];if(!rows.length)return{ok:true,programScores:[],storageMode:"local_only"};const identity=readRequester(storage),teamId=pendingTeam(rows[0]),parts=pendingOwner(storage,KEY,identity);if(identity&&teamId)savePending(storage,KEY,[...new Set([...(parts?.[1]===teamId?parts:[identity,teamId]),...rows.filter((row)=>pendingTeam(row)===teamId).map(pendingId).filter(Boolean)])]);const body=await request("POST",{program_scores:rows}),confirmed=Array.isArray(body?.program_scores)?body.program_scores:[];reconcilePendingProgramScoreRows({storage,requester:identity,localRows:parseStored(storage,"sl:program-scores",rows),remoteRows:confirmed});return{ok:true,storageMode:signedStorageMode(body),programScores:confirmed}};
  const deletePlayerProgramScores=async({teamId="",playerIdentity=""}={})=>{const teamIdValue=String(teamId||"").trim(),playerIdentityValue=normalizeIdentity(playerIdentity);if(!teamIdValue||!playerIdentityValue)throw new Error("program_score_delete_identity_required");const body=await request("DELETE",{team_id:teamIdValue,player_identity:playerIdentityValue}),parts=pendingOwner(storage,KEY);if(parts?.[1]===teamIdValue){const local=parseStored(storage,"sl:program-scores",[]),keep=(Array.isArray(local)?local:[]).filter((row)=>parts.includes(pendingId(row),2)&&pendingTeam(row)===teamIdValue&&player(row)!==playerIdentityValue).map(pendingId);savePending(storage,KEY,[parts[0],parts[1],...keep])}return{ok:true,storageMode:signedStorageMode(body),deletedCount:Number(body?.deleted_count||0)}};
  return{loadProgramScores,upsertProgramScores,deletePlayerProgramScores};
}
