import {normalizeIdentity,parseStored,readRequester,readSession,requestSignedBody,signedStorageMode,writeStored} from "./apiFetchBridge.js";
const id=r=>String(r?.id||"").trim(),team=r=>String(r?.team_id||r?.teamId||"").trim(),player=r=>normalizeIdentity(r?.email||r?.player_email||r?.playerEmail||r?.player_id||r?.playerId);
export const pendingOwner=(storage,key,requester="")=>{let m;try{m=String(storage?.getItem?.(key)||"")}catch{return null}const s=readSession(storage),r=normalizeIdentity(requester)||readRequester(storage);return m.startsWith(`${r}\t`)&&(!s?.rp||m.startsWith(`${s.rp}\t`))?m.split("\t"):null};
const save=(storage,key,p)=>writeStored(storage,key,p[2]?p.join("\t"):null);
export function reconcilePendingIds({storage,key,requester="",teamId="",localRows=[],remoteRows=[],own=false}={}){const remote=Array.isArray(remoteRows)?remoteRows:[],p=pendingOwner(storage,key,requester);if(!p||(teamId&&p[1]!==String(teamId||"").trim()))return remote;const local=(Array.isArray(localRows)?localRows:[]).filter(r=>{const i=id(r);return p.includes(i,2)&&!remote.some(x=>id(x)===i)&&team(r)===p[1]&&(!own||player(r)===p[0])});save(storage,key,[p[0],p[1],...local.map(id)]);return remote.concat(local)}
const mark=(storage,key,rows)=>{const r=readRequester(storage),t=team(rows[0]),p=pendingOwner(storage,key,r);if(r&&t)save(storage,key,[...new Set([...(p?.[1]===t?p:[r,t]),...rows.filter(x=>team(x)===t).map(id).filter(Boolean)])])};
export function createPendingScoreService({fetchImpl=globalThis?.fetch,storage=globalThis?.localStorage,path,field,key,own=false,name="scores",prefix="score",pendingFallback=false,scopeTeam}={}){
 const reconcile=o=>reconcilePendingIds({...o,key,own}),request=(method,data,teamId="")=>{if(typeof fetchImpl!=="function")throw new Error(`${prefix}_api_unavailable`);return requestSignedBody(fetchImpl,`${path}${teamId?`?team_id=${encodeURIComponent(teamId)}`:""}`,method,storage,data,`${prefix}_${method==="GET"?"load":method==="POST"?"write":"delete"}_failed`)};
 const load=async({teamId=""}={})=>{const local=parseStored(storage,key,[]),scope=own?"":teamId||scopeTeam?.(storage)||"";if(typeof fetchImpl!=="function")return{ok:false,unavailable:true,[name]:pendingFallback?reconcile({storage,requester:readRequester(storage),teamId:scope,localRows:local,remoteRows:[]}):[]};const body=await request("GET",null,String(teamId||"").trim()),remote=Array.isArray(body?.[field])?body[field]:[];return{ok:true,storageMode:signedStorageMode(body),[name]:reconcile({storage,requester:readRequester(storage),teamId:scope,localRows:local,remoteRows:remote})}};
 const upsert=async(rows=[])=>{rows=Array.isArray(rows)?rows:[rows];if(!rows.length)return{ok:true,[name]:[],storageMode:"local_only"};const requester=readRequester(storage);mark(storage,key,rows);const body=await request("POST",{[field]:rows}),confirmed=Array.isArray(body?.[field])?body[field]:[];reconcile({storage,requester,localRows:parseStored(storage,key,rows),remoteRows:confirmed});return{ok:true,storageMode:signedStorageMode(body),[name]:confirmed}};
 const remove=async({teamId="",playerIdentity=""}={})=>{const t=String(teamId||"").trim(),who=normalizeIdentity(playerIdentity);if(!t||!who)throw new Error(`${prefix}_delete_identity_required`);const body=await request("DELETE",{team_id:t,player_identity:who}),p=pendingOwner(storage,key);if(own){if(pendingOwner(storage,key,who)?.[1]===t)save(storage,key,[])}else if(p?.[1]===t)save(storage,key,[p[0],p[1],...(parseStored(storage,key,[])||[]).filter(r=>p.includes(id(r),2)&&team(r)===t&&player(r)!==who).map(id)]);return{ok:true,storageMode:signedStorageMode(body),deletedCount:Number(body?.deleted_count||0)}};
 return{load,upsert,remove,reconcile};
}
const KEY="sl:sp";
export const hasPendingScoreRows=(storage=globalThis?.localStorage,requester="")=>!!pendingOwner(storage,KEY,requester);
export function reconcilePendingScoreRows(options={}){return reconcilePendingIds({...options,key:KEY,own:true})}
export function createScorePersistenceService(options={}){const s=createPendingScoreService({...options,path:"/v1/scores",field:"scores",key:KEY,own:true});return{loadScores:s.load,upsertScores:s.upsert,deletePlayerScores:s.remove}}
