export const HELP_TOPICS = {
  logScore: {
    title: "Log Score",
    shortHint: "Pick the active drill and enter only completed reps for today.",
    details: [
      "Use your final made-shot total for the drill.",
      "If a drill has a max, keep entries at or below the cap.",
      "Tap More for reminders, then Got it to dismiss this tip.",
    ],
  },
  addEvent: {
    title: "Add Event",
    shortHint: "Create events with date, time, location, and a short prep note.",
    details: [
      "Title and date are required before creating an event.",
      "Use event type tags to keep the calendar scannable.",
      "Include arrival details in description to reduce player questions.",
    ],
  },
  teamCode: {
    title: "Team Code",
    shortHint: "Enter the exact invite code from your coach to join the correct team.",
    details: [
      "Codes are uppercase and can be regenerated by coaches.",
      "If code fails, ask the coach for a fresh invite code.",
      "Joining links your account to team drills, events, and leaderboards.",
    ],
  },
};
