create table if not exists public.shot_logs (
  id bigint generated by default as identity primary key,
  email text,
  name text,
  player_id text,
  team_id text,
  made numeric,
  date text,
  ts timestamptz default now()
);

alter table public.shot_logs add column if not exists id bigint generated by default as identity;
alter table public.shot_logs add column if not exists email text;
alter table public.shot_logs add column if not exists name text;
alter table public.shot_logs add column if not exists player_id text;
alter table public.shot_logs add column if not exists team_id text;
alter table public.shot_logs add column if not exists made numeric;
alter table public.shot_logs add column if not exists date text;
alter table public.shot_logs add column if not exists ts timestamptz default now();

alter table public.shot_logs
  alter column team_id type text using team_id::text,
  alter column player_id type text using player_id::text,
  alter column made type numeric using made::numeric;

create index if not exists idx_shot_logs_team_id on public.shot_logs(team_id);
create index if not exists idx_shot_logs_player_id on public.shot_logs(player_id);
create index if not exists idx_shot_logs_team_player on public.shot_logs(team_id, player_id);

notify pgrst, 'reload schema';
