import { enforceRateLimit, getClientKey } from "../../../_utils/security.js";
import { selectRows, updateRows } from "../../../_utils/supabase.js";
const encoder = new TextEncoder();
const normalizeEmail=v=>String(v||"").trim().toLowerCase();
const toHex=bytes=>Array.from(bytes).map(b=>b.toString(16).padStart(2,"0")).join("");
const safeProfile=row=>({email:row.email,name:row.name,role:row.role,team_id:row.team_id||null,hide_from_leaderboards:row.hide_from_leaderboards===true});
async function hashPassword(password,saltHex){const key=await crypto.subtle.importKey("raw",encoder.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:Uint8Array.from((saltHex||"").match(/../g)?.map(h=>parseInt(h,16))||[]),iterations:120000,hash:"SHA-256"},key,256);return toHex(new Uint8Array(bits));}

const CONFIG_ERROR_PATTERNS=["SUPABASE_URL_MISSING","SUPABASE_SERVICE_ROLE_KEY_MISSING"];
const TABLE_ERROR_PATTERNS=["legacy_auth_profiles","relation does not exist","schema cache","permission denied","REST_legacy_auth_profiles_FAILED","PGRST"];
const classifyLegacyAuthError=(error)=>{const message=String(error?.message||"");const details=JSON.stringify(error?.details||{});const haystack=`${message} ${details}`.toLowerCase();if(CONFIG_ERROR_PATTERNS.some(p=>haystack.includes(p.toLowerCase())))return"config_error";if(TABLE_ERROR_PATTERNS.some(p=>haystack.includes(p.toLowerCase())))return"table_error";return"internal_error";};
const sanitizeLegacyAuthMessage=error=>{const raw=String(error?.message||"unexpected error");return raw.replace(/password_hash|password_salt|password|SUPABASE_SERVICE_ROLE_KEY|service_role|apikey|authorization|bearer/gi,"[redacted]").slice(0,180);};
const handleLegacyAuthError=(endpoint,error)=>{const safeCode=classifyLegacyAuthError(error);const safeMessage=sanitizeLegacyAuthMessage(error);console.error("[legacy-auth] endpoint failure",{endpoint,status:"error",category:safeCode,safeCode,message:safeMessage});return Response.json({error:safeCode},{status:500});};

export async function onRequestGet(){return Response.json({ok:true,service:"legacy-auth-update-profile"});}
export async function onRequestPost({request,env}){try{const body=await request.json().catch(()=>({}));const email=normalizeEmail(body?.email);const password=String(body?.password||"");const rl=enforceRateLimit({key:`legacy_profile:${getClientKey(request,email)}`,max:20,windowMs:60_000});if(!rl.allowed)return Response.json({error:"rate_limited"},{status:429,headers:{"Retry-After":String(rl.retryAfterSeconds)}});if(!email||!password)return Response.json({error:"unauthorized"},{status:401});const rows=await selectRows(env,"legacy_auth_profiles",`select=email,password_hash,password_salt,name,role,team_id,hide_from_leaderboards&email=eq.${encodeURIComponent(email)}&limit=1`).catch(()=>[]);const row=Array.isArray(rows)?rows[0]:null;if(!row)return Response.json({error:"unauthorized"},{status:401});const computed=await hashPassword(password,row.password_salt||"");if(computed!==row.password_hash)return Response.json({error:"unauthorized"},{status:401});const patch={updated_at:new Date().toISOString()};if(body?.name!==undefined)patch.name=String(body.name||"").trim();if(body?.role!==undefined){const role=String(body.role||"").trim().toLowerCase();if(role!=="coach"&&role!=="player")return Response.json({error:"invalid_request"},{status:400});patch.role=role;}if(body?.team_id!==undefined)patch.team_id=body.team_id?String(body.team_id).trim():null;if(body?.hide_from_leaderboards!==undefined)patch.hide_from_leaderboards=body.hide_from_leaderboards===true;const hasUserFields=Object.keys(patch).length>1;if(!hasUserFields)return Response.json({profile:safeProfile(row)});const updated=await updateRows(env,"legacy_auth_profiles",`email=eq.${encodeURIComponent(email)}&select=email,name,role,team_id,hide_from_leaderboards`,patch).catch(()=>[]);const out=updated?.[0]||row;return Response.json({profile:safeProfile(out)});}catch(error){return handleLegacyAuthError("/v1/legacy-auth/update-profile",error);}}
