import ShotLabIcon from "./ShotLabIcon";
import "./SecondaryPageSystem.css";
const ICONS=[[/player|roster/,"team"],[/event|schedule|calendar/,"calendar"],[/career|profile/,"profile"],[/leader|rank/,"trophy"],[/store/,"store"],[/progress|analytic/,"chart"],[/coach|assignment/,"coach"],[/training|drill/,"training"]];
const iconFor=value=>ICONS.find(([pattern])=>pattern.test(String(value).toLowerCase()))?.[1]||"target";
const actionClassName=(index,action)=>["secondaryPageAction",index?"secondaryPageAction--secondary":"secondaryPageAction--primary",action.className].filter(Boolean).join(" ");
export function SecondaryPageShell({children,testId,className=""}){return <section className={["secondaryPageShell",className].filter(Boolean).join(" ")} data-testid={testId}>{children}</section>}
export function SecondaryPageIntro({eyebrow,title,summary,status,actions=[],testId,icon}){const iconName=icon||iconFor(`${eyebrow} ${title}`);return <header className="secondaryPageIntro appHeader" data-testid={testId}><span className="secondaryPageIntro__icon" aria-hidden="true"><ShotLabIcon name={iconName} size={28}/></span><div className="secondaryPageIntro__copy">{eyebrow?<div className="secondaryPageIntro__eyebrow">{eyebrow}</div>:null}<h1 className="secondaryPageIntro__title appHeaderTitle">{title}</h1>{summary?<p className="secondaryPageIntro__summary">{summary}</p>:null}</div>{status||actions.length?<div className="secondaryPageIntro__actions">{status?<div className="secondaryPageIntro__status" aria-live="polite">{status}</div>:null}<div className="secondaryPageIntro__buttonRow">{actions.map((action,index)=><button key={action.key||action.label} type="button" className={actionClassName(index,action)} onClick={action.onClick} disabled={action.disabled} aria-label={action.ariaLabel||action.label}><span>{action.label}</span>{action.icon?<span className="secondaryPageAction__icon" aria-hidden="true">{action.icon}</span>:index===0?<ShotLabIcon name="arrow" size={16}/>:null}</button>)}</div></div>:null}</header>}
export function SecondaryPageToolbar({children,testId,label="Page tools"}){return <section className="secondaryPageToolbar" data-testid={testId} aria-label={label}>{children}</section>}
export function SecondaryPageDecision({eyebrow,title,detail,tone="neutral",action,children,testId,icon}){return <section className="secondaryPageDecision" data-tone={tone} data-testid={testId}><span className="secondaryPageDecision__icon" aria-hidden="true"><ShotLabIcon name={icon||iconFor(`${eyebrow} ${title}`)} size={23}/></span><div className="secondaryPageDecision__copy">{eyebrow?<div className="secondaryPageDecision__eyebrow">{eyebrow}</div>:null}<h2>{title}</h2>{detail?<p>{detail}</p>:null}{action?<button type="button" onClick={action.onClick} disabled={action.disabled}><span>{action.label}</span><ShotLabIcon name="arrow" size={16}/></button>:null}</div>{children?<div className="secondaryPageDecision__visual">{children}</div>:null}</section>}
export function SecondaryPageEvidence({children,testId,label="Supporting evidence"}){return <section className="secondaryPageEvidence" data-testid={testId} aria-label={label}>{children}</section>}
