import { enforceRateLimit, getClientKey } from "../../../_utils/security.js";
import { selectRows, upsertRows } from "../../../_utils/supabase.js";
const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/; const encoder = new TextEncoder();
const normalizeEmail=v=>String(v||"").trim().toLowerCase();
const toHex=bytes=>Array.from(bytes).map(b=>b.toString(16).padStart(2,"0")).join("");
const safeProfile=row=>({email:row.email,name:row.name,role:row.role,team_id:row.team_id||null,hide_from_leaderboards:row.hide_from_leaderboards===true});
async function hashPassword(password,saltHex){const key=await crypto.subtle.importKey("raw",encoder.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:Uint8Array.from(saltHex.match(/../g).map(h=>parseInt(h,16))),iterations:120000,hash:"SHA-256"},key,256);return toHex(new Uint8Array(bits));}
export async function onRequestGet(){return Response.json({ok:true,service:"legacy-auth-register"});}
export async function onRequestPost({request,env}){const body=await request.json().catch(()=>({}));const email=normalizeEmail(body?.email);const password=String(body?.password||"");const name=String(body?.name||"").trim();const role=String(body?.role||"").trim().toLowerCase();const rl=enforceRateLimit({key:`legacy_register:${getClientKey(request,email)}`,max:8,windowMs:60_000});if(!rl.allowed)return Response.json({error:"rate_limited"},{status:429,headers:{"Retry-After":String(rl.retryAfterSeconds)}});if(!EMAIL_RE.test(email)||!name||(role!=="coach"&&role!=="player")||password.length<8)return Response.json({error:"invalid_request"},{status:400});const existing=await selectRows(env,"legacy_auth_profiles",`select=email&email=eq.${encodeURIComponent(email)}&limit=1`).catch(()=>[]);if(Array.isArray(existing)&&existing.length>0)return Response.json({error:"account_exists"},{status:409});const saltHex=toHex(crypto.getRandomValues(new Uint8Array(16)));const hashHex=await hashPassword(password,saltHex);const inserted=await upsertRows(env,"legacy_auth_profiles",{email,password_hash:hashHex,password_salt:saltHex,name,role,team_id:null,hide_from_leaderboards:false},"email");return Response.json({profile:safeProfile(inserted?.[0]||{email,name,role,team_id:null,hide_from_leaderboards:false})});}
