export default function buildCoachRouteConfig({
  user,
  myTeam,
  regenerateJoinCode,
  updateTeamBranding,
  addRosterPlayer,
  playerProfiles,
  drills,
  programDrills,
  scopedScores,
  scopedPlayers,
  updateDrill,
  addDrill,
  removeDrill,
  addProgramDrill,
  removeProgramDrill,
  scopedEvents,
  scopedRsvps,
  addEvent,
  removeEvent,
  removeRsvp,
  addRsvp,
  scopedScSessions,
  scopedScRsvps,
  scopedScLogs,
  addScSession,
  removeScSession,
  scopedShotLogs,
  logout,
  deleteAccount,
}) {
  return {
    u: user,
    team: myTeam,
    teamId: user?.teamId,
    regenerateJoinCode,
    updateTeamBranding,
    addRosterPlayer,
    playerProfiles,
    drills,
    programDrills,
    scores: scopedScores,
    players: scopedPlayers,
    updateDrill,
    addDrill,
    removeDrill,
    addProgramDrill,
    removeProgramDrill,
    events: scopedEvents,
    rsvps: scopedRsvps,
    addEvent,
    removeEvent,
    removeRsvp,
    addRsvp,
    scSessions: scopedScSessions,
    scRsvps: scopedScRsvps,
    scLogs: scopedScLogs,
    addScSession,
    removeScSession,
    shotLogs: scopedShotLogs,
    logout,
    deleteAccount,
  };
}
