import React from "react";
export const DS_TOKENS = { radius: { sm: 10, md: 12, lg: 14, xl: 16 }, spacing: { xs: 6, sm: 8, md: 10, lg: 12, xl: 14, xxl: 16 }, shadow: { card: "var(--shadow-1)", elevated: "0 8px 24px rgba(0,0,0,0.45)", glow: "0 8px 24px color-mix(in srgb,var(--accent) 28%, transparent)" }, transition: { base: "160ms ease", fast: "120ms ease" }, gradient: { surface: "linear-gradient(165deg, rgba(255,255,255,0.04), rgba(0,0,0,0.28))", accent: "linear-gradient(145deg, color-mix(in srgb,var(--accent) 17%, transparent), rgba(9,11,14,0.92) 58%)" } };
const BASE_BUTTON = { minHeight: 40, borderRadius: DS_TOKENS.radius.md, padding: "10px 14px", cursor: "pointer", fontWeight: 700, letterSpacing: "0.03em", textTransform: "uppercase", transition: `transform ${DS_TOKENS.transition.fast}, border-color ${DS_TOKENS.transition.base}, background ${DS_TOKENS.transition.base}, color ${DS_TOKENS.transition.base}` };
export function DSButton({ variant = "secondary", style, ...props }) { const variants = { primary: { border: "1px solid var(--accent)", background: "var(--accent)", color: "#0B0D10", boxShadow: DS_TOKENS.shadow.glow }, secondary: { border: "1px solid var(--stroke-1)", background: "var(--surface-1)", color: "var(--text-2)" }, ghost: { border: "1px solid transparent", background: "transparent", color: "var(--text-2)" } }; return <button {...props} style={{ ...BASE_BUTTON, ...(variants[variant] || variants.secondary), ...style }} />; }
export function DSCard({ children, style, accent = false, ...props }) { return <div {...props} style={{ borderRadius: DS_TOKENS.radius.lg, border: "1px solid var(--stroke-1)", background: accent ? DS_TOKENS.gradient.accent : DS_TOKENS.gradient.surface, boxShadow: DS_TOKENS.shadow.card, ...style }}>{children}</div>; }
export function DSMetricCard({ label, value, onClick, style, valueStyle }) { return <button type="button" onClick={onClick} style={{ minHeight: 72, borderRadius: DS_TOKENS.radius.lg, border: "1px solid color-mix(in srgb, var(--accent) 12%, var(--stroke-1))", background: "linear-gradient(165deg, rgba(255,255,255,0.06), rgba(0,0,0,0.32) 62%)", padding: "12px", display: "flex", flexDirection: "column", justifyContent: "center", textAlign: "left", cursor: "pointer", ...style }}><div style={{ fontSize: 10, fontWeight: 700, letterSpacing: "0.05em", color: "var(--text-tertiary)", textTransform: "uppercase" }}>{label}</div><div style={{ marginTop: 6, fontSize: 24, lineHeight: 1, color: "var(--text-1)", ...valueStyle }}>{value}</div></button>; }
export function DSSectionHeader({ title, meta }) { return <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8, marginBottom: 10 }}><div style={{ color: "var(--text-1)", fontSize: 12, fontWeight: 800, letterSpacing: "0.07em", textTransform: "uppercase" }}>{title}</div>{meta ? <div style={{ color: "var(--text-3)", fontSize: 10, fontWeight: 700, letterSpacing: "0.04em", textTransform: "uppercase" }}>{meta}</div> : null}</div>; }
export function DSChip({ active, children, style, ...props }) { return <button type="button" {...props} style={{ minHeight: 38, borderRadius: DS_TOKENS.radius.sm, border: `1px solid ${active ? "var(--accent)" : "var(--stroke-1)"}`, background: active ? "var(--accent-soft)" : "var(--surface-2)", color: active ? "var(--accent)" : "var(--text-2)", fontSize: 11, fontWeight: 700, padding: "0 10px", textTransform: "uppercase", cursor: "pointer", ...style }}>{children}</button>; }
export function DSInput({ style, ...props }) { return <input {...props} style={{ minHeight: 40, borderRadius: DS_TOKENS.radius.md, border: "1px solid var(--stroke-1)", background: "var(--surface-1)", color: "var(--text-1)", padding: "10px 12px", ...style }} />; }
export function DSEmptyState({ title, message, style }) { return <div style={{ borderRadius: DS_TOKENS.radius.md, border: "1px solid var(--stroke-1)", background: "var(--surface-2)", color: "var(--text-2)", fontSize: 13, padding: "16px 14px", fontWeight: 600, ...style }}><div style={{ color: "var(--text-1)", fontWeight: 700, marginBottom: 4 }}>{title}</div><div>{message}</div></div>; }

export function DSLoadingState({ label = "Loading", style }) { return <div role="status" aria-live="polite" style={{ borderRadius: DS_TOKENS.radius.md, border: "1px solid var(--stroke-1)", background: "var(--surface-2)", color: "var(--text-2)", fontSize: 12, padding: "12px 14px", fontWeight: 700, letterSpacing: "0.04em", textTransform: "uppercase", ...style }}>{label}…</div>; }
